import {api } from 'lwc';
import LwcBaseWidget from 'c/lwcBaseWidget';
import componentTemplate from './lwcHubspotForm.html';


export default class LwcHubspotForm extends LwcBaseWidget {

    @api formUrl='';

     //title of the toast messages generated by the component
    interopActionCompletedEventMessageTitle = '';

    //actual template of the component
    actualComponentTemplate = componentTemplate;


    connectedCallback() {
        this.setActionCompleted();
    }


  
    

}