{
    "recordCount": 2,
    "data": [
        {
            "id": 1,
            "name": "Denver Design Center",
            "isActive": true,
            "salesAgents": [
                {
                    "id": 1,
                    "userId": 1,
                    "isActive": true
                }
           ],
            "reportingCity": "Fairfax",
            "reportingCommunity": ""
        },
        {
            "id": 999999,
            "name": "Test Design Center",
            "isActive": true,
            "salesAgents": [
                {
                    "id": 999999,
                    "userId": 1,
                    "isActive": true
                }
           ],
            "reportingCity": "Fairfax",
            "reportingCommunity": ""
        }
    ]
}