{
    "recordCount": 1,
    "data": [
        {
            "id": 999999,
            "salesOfficeId": 999999,
            "name": "50 Ann - Bolton",
            "isActive": true,
            "adjLumpSum": 0,
            "adjLotPrice": 0,
            "adjLotPremium": 0,
            "adjModelPrice": 0,
            "adjOptions": 0,
            "adjMortgage": 0,
            "salesPriceType": "PostTax1Rebate",
            "salesAgents": [
                {
                    "id": 999999,
                    "userId": 999999,
                    "isActive": true
                }
           ]
        }
    ]
}