{
    "notification": {
        "eventType": "PendingOffer",
        "eventDate": "2019-05-16T17:00:07.687",
        "parameters": [
            {
                "name": "opportunityExternalId",
                "value": "999999"
            },
            {
                "name": "eventMessage",
                "value": "Contract is Ready"
            },
            {
                "name": "lotPrice",
                "value": 4999
            },
            {
                "name": "lotPremium",
                "value": 4998
            },
            {
                "name": "baseModelPrice",
                "value": 40000
            },
            {
                "name": "totalOptionsAmount",
                "value": 850.99
            },
            {
                "name": "totalDiscountAmount",
                "value": 80
            },
            {
                "name": "totalTaxAmount",
                "value": 82.13
            },
            {
                "name": "totalTaxRebateAmount",
                "value": 800
            },
            {
                "name": "totalSaleAmount",
                "value": 807437.12
            }
        ]
    }
}