{
    "recordCount": 1,
    "data": [
        {
            "id": 999999,
            "subdivisionId": 999999,
            "lotNumber": "050001",
            "address": "TBD Mayapple Court",
            "city": "Bristow",
            "applicableModels": null,
            "lotType": "Regular",
            "availabilityStatus": "Open",
            "basePrice": 0,
            "premium": 10000,
            "baseModelPriceOverride": null,
            "releasedForSale": true,
            "releasedForConstruction": false,
            "releaseDate": "2019-07-04T00:00:00",
            "modelId": 999999,
            "totalOptionsAmount": null
        }
    ]
}