{
  "id": 35038,
  "customer": {
    "id": 888888,
    "firstName": "Test_F",
    "lastName": "Test_L",
    "streetAddress1": "75 Frontenac Drive",
    "streetAddress2": "West Wing",
    "city": "Markham",
    "stateProvinceId": 52,
    "zipPostalCode": "L3R 6H2",
    "homeEmail": "Test@constellationhb.com",
    "workEmail": "Test@constellationhb.com",
    "homePhone": "111-111-2199",
    "workPhone": "222-222-3299",
    "mobilePhone": "333-333-4399",
    "status": "Selection",
    "externalId": "003m000000hp96oBBB"
  },
  "coBuyers": [
  ],
  "subdivisionId": 1,
  "modelId": 1,
  "lotId": 35,
  "swing": "Right",
  "isInvestment": false,
  "salesAgentId": 1,
  "contingencies": [
    {
      "id": 0,
      "typeId": 1,
      "expiryDate": "2018-06-15T00:00:00",
      "metDate": null,
      "notes": "from salesforce 1",
      "externalId": "003m000000hp96oC111"
    },
    {
      "id": 0,
      "typeId": 3,
      "expiryDate": "2018-07-10T00:00:00",
      "metDate": null,
      "notes": "from salesforce 2",
      "externalId": "003m000000hp96oC222"
    }
  ],
  "realEstateAgentId": 1,
  "selectionDate": "2019-04-11T00:00:00",
  "closingTargetDate": "2019-06-15T00:00:00",
  "closingType": "Tentative",
  "firstVisitDate": "2019-07-22T00:00:00",
  "externalId": "003m000000hp96oC_KC"
}
