{
    "recordCount": 1,
    "data": [
        {
            "id": 999999,
            "name": "353-1 Taylor",
            "elevation": "1",
            "code": "3530",
            "isActive": true,
            "squareFootage": 2171,
            "bedrooms": 4,
            "fullBaths": 1,
            "halfBaths": 1,
            "garageCapacity": 2,
            "baseModelPrice": 350000
        }
    ]
}