{
    "recordCount": 2,
    "data": [
        {
            "id": 1,
            "username": "Admin",
            "firstName": "ADMIN",
            "lastName": "ADMIN",
            "isActive": true
        },
        {
            "id": 999999,
            "username": "salesadmintor",
            "firstName": "Sales",
            "lastName": "Admin (Toronto)",
            "isActive": true
        }
   ]
}